### ISSUE TITLE
Print_Master_Reactions_List.pl requires genEquationCode() method

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ModelSEEDDatabase#1]
Just a reminder that the Print_Master_Reactions_List.pl script requires a Bio::KBase::ObjectAPI::KBaseBiochem::Reaction object that has a genEquationCode() method.

**Comment by samseaver** [comment]
You will find that function in this branch in my fork:

https://github.com/samseaver/KBaseFBAModeling/tree/CompartmentFree

At some point, I have to merge the master branch with this, but I need to double-check everything will still work.

**Comment by samseaver** [comment]
So, I was able to pull updates for the master branch of KBaseFBAModeling and then merge the CompartmentFree branch in my fork. However, I just realized that though I've been working on using the API available in KBaseFBAModeling, ProbModelSEED has its own copy of the API.

So, @cshenry the question is, moving forward, while developing the biochemistry in ModelSEEDDatabase, should I use KBaseFBAModeling or ProbModelSEED?

**Comment by chian** [comment]
I would assume ProbModelSEED moving forward

**Comment by cshenry** [comment]
Really, you should try and keep corrections posted in both. But ProbModelSEED is the priority.

**Comment by mmundy42** [comment]
This is resolved by ModelSEED/ProbModelSEED#41.
