### ISSUE TITLE
PlaceHolder for discussing issues in building ModelTemplates

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEEDDatabase#11]
In https://github.com/ModelSEED/ModelSEEDDatabase/commit/ccf61646bcde2951db74870df8414ac03f080035 I submitted a script for building the ModelTemplates from the data downloaded from the workspace. It's not finished.

Major points:
1.  I believe I have every field in every sub-object defined here, so even if it's empty (or set to a default value in some cases), it should be present in the resulting JSON object.
2.  I've not yet made an effort to define references and identifiers, and I'll likely add a section to the ReadMe to document/discuss this. So for now, the object's biochemistry is largely unconnected. For the same reason, the compcompartments list is undefined, as it would be full of duplicates.
3.  The compartments are defined in the ModelTemplate, but, by reading in the master reactions file, I'm reading generalized reactions, so I will need to expand the script to read in the reagent compartmentalization from the default files. This will have to serve as a starting point for the compartmentalization but ultimately, each ModelTemplate will be taken in its own direction, and the default files will be made redundant.
4.    Both Aliases (needs coding in the default files) and Pathways have not been done yet.

**Comment by mmundy42** [comment]
Question on aliases, there is an Aliases directory that has list of aliases from lots of sources.  And there are also aliases fields in the reaction and compound files.  Should aliases be defined separately in files in the Aliases directory?

**Comment by samseaver** [comment]
Thing about Aliases, is that I was going to fill the reaction and compound aliases using the files in Aliases, but hadn't gotten round to adding that part of the script.

Like the compounds, there's a small number of aliases that don't match between default and plantdefault so that will be useful as part of the curation process. It does also mean that if you were to add them now, you'll get some cross-talk.

**Comment by JamesJeffryes** [comment]
@samseaver Are you content closing this issue based on our reorg?

**Comment by samseaver** [comment]
Yep
