### ISSUE TITLE
move database ids to separate fields

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ModelSEEDDatabase#12]
Creating this ticket as a reminder.  It would be easier and probably more scalable to have KEGG, Metacyc, and AraCyc ids as their own fields, instead of being in aliases.

**Comment by mmundy42** [comment]
@nconrad, do you want the KEGG, MetaCyc, and AraCyc IDs as there own fields for the SOLR schema?    I'm assuming that you don't need the biochemistry object updated.

**Comment by nconrad** [comment]
Yeah, I think that is a good idea for ease of use and scalability.  Users
also want those ids often from what I understand.

Right, I haven't used the biochem objects yet.

On Wednesday, August 19, 2015, Mike Mundy notifications@github.com wrote:

> @nconrad https://github.com/nconrad, do you want the KEGG, MetaCyc, and
> AraCyc IDs as there own fields for the SOLR schema? I'm assuming that you
> don't need the biochemistry object updated.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ModelSEED/ModelSEEDDatabase/issues/12#issuecomment-132751953
> .

## 

---

t. 815-508-7951
e. nealconrad@gmail.com
