### ISSUE TITLE
Lots of reactions with status CPDFORMERROR

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ModelSEEDDatabase#13]
In the master reactions file there are 34,701 eactions of which 6,350 have a status of CPDFORMERROR.  The CPDFORMERROR status is set when at least one compound in the reaction does not have a formula or the formula is determined to be invalid.  All of the reactions with status CPDFORMERROR are because of the no formula condition.

A quick check showed that some of the reactions are transport reactions for the compound.  For example, rxn39240 has stoichiometry `-1:cpd30677:0:0:"D-Glucosamine Hydrochloride";1:cpd30677:1:0:"D-Glucosamine Hydrochloride"`.  It has status OK before running the Update_Reaction_Status.pl script but has status CPDFORMERROR after because D-Glucosamine Hydrochloride does not have a formula in the master compounds file.

In the master compounds file there are 27,692 compounds of which 5,068 do not have a formula.

Should there be a special case for transport reactions so that reactions that are transporting one compound between compartments have a status of OK even if there is no compound formula?

Otherwise the reactions aren't going to be usable for models.

**Comment by samseaver** [comment]
I'd originally thought that all compounds were negated where possible anywhere, before checking formula, so all simply transport reactions should've been marked as OK, I'll check the code.

**Comment by samseaver** [comment]
OK, based on these commits, I consider this issue to be closed:

https://github.com/ModelSEED/ModelSEEDDatabase/commit/5bfbce792d7f62660f40b4a2bbb2177f723d76a4
