### ISSUE TITLE
What data should be included in a compartment-free Biochemistry object?

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ModelSEEDDatabase#16]
Currently a Biochemistry object has the following data:
- compounds
- reactions
- compartments
- cues
- compoundSets
- reactionSets
- compound_aliases
- reaction_aliases

Questions:
1. With reactions defined in a compartment-free notation, are compartments still needed in the Biochemistry or can they only be included in Model Templates?
2. Do we need to define source files for cues, compoundSets, and reactionSets so they can be included in the Biochemistry?
3. Does the Biochemistry object need to include compound_aliases and reaction_aliases or do the aliases only need to be available via SOLR?

**Comment by janakagithub** [comment]
Does the Biochemistry object need to include compound_aliases and reaction_aliases or do the aliases only need to be available via SOLR
I would want to see the compound and reaction aliases intact in the biochemistry object. When we use biochemistry object for analysis, in most cases, it is through aliases that we recognize the compounds and reactions

**Comment by chian** [comment]
In theory, compartments can go provided old models can link back to the old biochemistry. I would prefer to see them to go and for us to go all compartment free.

**Comment by JamesJeffryes** [comment]
This is out of date and was discussed at the jam session so I'm closing this issue
