### ISSUE TITLE
Understanding releases

### ISSUE THREAD

**Issue by Midnighter** [ModelSEED/ModelSEEDDatabase#174]
Hi,

As some of you are aware, I'm working with @eladnoor to apply the component contribution method to the entire MetaNetX database and thus extend the content in equilibrator. We are successfully doing this for all compounds already. Now I'm working on bringing in reactions as well and since MetaNetX does not provide the common names, I am pulling in reaction names from your database. (I'm very happy that you provide the structured JSON in addition to your tables, by the way :wink: )

I would like to have a definitive reference for the version of the ModelSEED database. So I'm wondering if I should download the information from the releases (basically git tags) or simply use the latest commit hash when I do pull in the information.

Thanks for any pointers.

**Comment by samseaver** [comment]
Moritz,

We were just talking about that this week. We've never published the biochemistry on its own, only in conjunction with the original ModelSEED and PlantSEED papers. As such, we are very close to a full release of the current version, which we are calling v3, which I will tag as such. But none of the prior tags are currently "good".

The latest version you're probably interested in is the HEAD of the dev branch, and I'm confident that we'll not be making any more changes to the biochemistry itself, but I can't promise you that we won't be any last changes before we "release" the biochemistry as v3.0.

Sam

**Comment by Midnighter** [comment]
Excellent, good to know.
