### ISSUE TITLE
Placeholder issue for decisions regarding use of reaction identifiers in ModelTemplate

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEEDDatabase#18]
I'm currently starting to re-build the Plant ModelTemplate. Its not so much that I'm changing the list of reactions, but I'm changing how compartmentalization is assigned to reactions, as there'll be some manual curation to that effect.

I'm doing this with the current version of the ModelTemplate, pending any changes made to the new version that'll be published with ProbModelSEED, but it serves a way for me to organize the data in the meantime.

But the whole point of this issue is that I'm also bearing in mind that we're working towards a unified and compartment-free biochemistry, and as such, I'm trying to anticipate which reaction identifiers I should use. 

In the case where two identical reactions are otherwise in different compartments, I will use the reaction id with the lowest number. In the ModelTemplate, I will create duplicate template reactions, but otherwise assign different compartments.

To an extent, this is obvious, but I wanted to be explicit about it.

**Comment by JamesJeffryes** [comment]
Hey Sam, can I close this as an issue as it something that you've already done?

**Comment by samseaver** [comment]
Yes.
