### ISSUE TITLE
odd reaction 1281967929

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ModelSEEDDatabase#23]
@chian reports:

 I have a reaction name “1281967929” with an ID "CoA-2-methylpropanoylating)” and an EQ "(1) 3-Methyl-2-oxobutanoate[c] + (1) CoA[c] + (1) Oxidizedferredoxin[c] <=> (1) CO2[c] + (1) Isobutyryl-CoA[c] + (1) Reducedferredoxin[c]”

(see http://modelseed.theseed.org/biochem/)

**Comment by janakagithub** [comment]
I am familiar with this reaction in Valine degradation with the exception that it uses NAD/NADH instead of ferredoxin. EC 1.2.1.25 --  2-oxoisovalerate dehydrogenase (acylating). This reaction may be a variant of that.

**Comment by nconrad** [comment]
In any case, the reaction probably needs to be sanitized (trailing paren and possibly wrong ID).

**Comment by samseaver** [comment]
I'd already intentionally removed it from the reactions.master.tsv file.
It's properly formatted complement is rxn13962. It's preserved in a dump of
the old biochemistry: ../Biochemistry/reactions.default.cf.tsv

On Wed, Oct 28, 2015 at 2:36 PM, nconrad notifications@github.com wrote:

> In any case, the reaction probably needs to be sanitized (trailing paren
> and possibly wrong ID).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ModelSEED/ModelSEEDDatabase/issues/23#issuecomment-151967161
> .

## 

Asst. Computational Scientist
Mathematics and Computer Science Division
Biosciences Division
Argonne National Laboratory
9700 S. Cass Avenue
Argonne, IL 60439

http://www.linkedin.com/pub/sam-seaver/0/412/168
samseaver@gmail.com
(773) 796-7144

"We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time."
   --T. S. Eliot

**Comment by JamesJeffryes** [comment]
@samseaver Sounds like you resolved this issue, may I close it?

**Comment by samseaver** [comment]
Yep
