### ISSUE TITLE
modelSEED model not annotated

### ISSUE THREAD

**Issue by ensakz** [ModelSEED/ModelSEEDDatabase#232]
Hi,

I am having trouble with navigating with modelSEED model since it has IDs different from IDs of BiGG-based models (sample reaction ID in my model is rxn00974_c0). Unfortunately, the modelSEED model which I am using is not well annotated so its comparison with BiGG model is not straightforward. I just heard that I can use modelSEED database (such as https://github.com/ModelSEED/ModelSEEDDatabase/blob/master/Biochemistry/reactions.json) to annotate my model. Therefore, my question is reaction identifiers from current version of ModelSEED database are still the same as for my model?

Please refer to the model is attached to this issue.

Best regards,
Sanzhar
[Methylocystis_hirsuta.zip](https://github.com/ModelSEED/ModelSEEDDatabase/files/5374881/Methylocystis_hirsuta.zip)

**Comment by samseaver** [comment]
Dear Sanzhar,

First of all, yes, the biochemistry for all metabolic reconstructions for ModelSEED is derived from our biochemistry database found in this repository, and all the reactions will have the identifier format of rxnnnnnn (where n is a digit). The c0 suffix represents the compartment the reaction is found in.

Secondly, if you're concerned about mapping between BiGG and ModelSEED identifiers, you can find which BiGG reactions are linked to our ModelSEED reactions here:
https://github.com/ModelSEED/ModelSEEDDatabase/blob/master/Biochemistry/Aliases/Unique_ModelSEED_Reaction_Aliases.txt

**Comment by ensakz** [comment]
@samseaver Thanks for the reply
