### ISSUE TITLE
URL for linking to ModelSEED compounds and reactions?

### ISSUE THREAD

**Issue by djinnome** [ModelSEED/ModelSEEDDatabase#27]
Hi folks,

  I would like to link MetaCyc reactions and compounds to their equivalents in ModelSEED. Is there a ModelSEED website that has a unique URL for each compound or reaction identifier?  The URL for the Aliases file in Github could sort of work, but I was hoping for something a bit more permalink like.

If not, when do you anticipate there will be one?

Sincerely,

Jeremy

**Comment by samseaver** [comment]
Jeremy,

We don't have permalinks yet available in ModelSEED.  You can retrieve the data for the individual compound and reaction entities via the PATRIC REST API.

But this won't give you a well-formatted table, so I doubt that you'd want use it.

@nconrad : Can you comment on when/whether this feature may be possible?

**Comment by nconrad** [comment]
Hi Jeremy,

I should be able to add this before next week.  Note that the data displayed may not be final/complete, but I can at least add the URLs for you.  Sound good?

Please don't use the PATRIC API. It's not intended to be used externally right now.

-Neal

**Comment by djinnome** [comment]
Thanks so much! I think this will be a valuable addition to ModelSEED. Also, I don't know if you guys are the right people to talk to about this, but I noticed that a lot of the ModelSEED compounds that were in the MetaCyc.aliases file are not present in KBase.  For example, none of the carbon sources in the attached file could be uploaded  as part of a PhenotypeSet, even though they are clearly in ModelSEED:
[missing_cpds_from_kbase.txt](https://github.com/ModelSEED/ModelSEEDDatabase/files/141198/missing_cpds_from_kbase.txt)

**Comment by samseaver** [comment]
We are working on updating the biochemistry in KBase, but do note, there isn't going to be a tight synchronization between ModelSEEDDatabase and KBase. Nor will there be so between the public databases like MetaCyc and KEGG, and ModelSEEDDatabase itself, at least not for the foreseeable future.

**Comment by djinnome** [comment]
OK, fair enough. Given that there isn't going to be a tight synchronization between ModelSEED and KBase, Is there a way that I can query KBase to find out what compounds and reactions are currently in it?

**Comment by samseaver** [comment]
Due to the size of the biochemistry, it hadn't been straight-forward to make it readily available via a KBase narrative, but we keep a couple of tables at an FTP site:

ftp://ftp.kbase.us/assets/KBase_Reference_Data/Biochemistry/

**Comment by nconrad** [comment]
@djinnome, I added permalinks for reactions and compounds.

You can see the links at http://modelseed.org/biochem . The urls are of the form /biochem/compounds/$compound_id and biochem/reactions/$reaction_id

**Comment by djinnome** [comment]
Thanks!
