### ISSUE TITLE
Invalid value in deltag and deltagerr fields

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ModelSEEDDatabase#3]
There are 1088 compounds in the Biochemistry/compounds.default.tsv and Biochemistry/compounds.master.tsv files where the value of the the deltag field is "deltaG" and the value of the deltagerr field is "deltaGErr". Should the values be reset to 10000000 to indicate the value is unknown?

**Comment by mmundy42** [comment]
In Biochemistry/reactions.master.tsv there are 68 reactions where the value of the deltag field is "deltaG" and 63 reactions where the value of the deltagerr field is "deltaGErr".

In Biochemistry/reactions.default.tsv there are 621 reactions where the value of the deltag field is "deltaG" and 455 reactions where the value of the deltagerr field is "deltaGErr".

**Comment by samseaver** [comment]
This shouldn't be appearing, I should have checked more closely. The function that updates the values so that they should read "null" is not recognizing specific unusual instances and prints the column name instead.

**Comment by samseaver** [comment]
Fixed in https://github.com/ModelSEED/ModelSEEDDatabase/commit/cb304d53b03d1c3a8bad86a40f26fd7aa294c544

**Comment by samseaver** [comment]
I'm re-opening this as a placeholder for dealing with default values in the biochemistry.  It occurred to me that right now we have 2, maybe 3 default values for deltag and deltagerr which are 'null', '10000000' and possibly '0' (I'm inclined to believe that '0' is not an actual result)

**Comment by mmundy42** [comment]
Confirmed that the original problem is fixed and deltag and deltagerr fields now have "null" instead of the column name.

I'd prefer to use "null" as the default value to be consistent with other columns.  In reactions.master.tsv there are 4,405 reactions with a deltag value of 0 and all of them have a deltagerr value of 2.  In compounds.master.tsv there are 63 compounds with a deltag value of 0 and 59 compounds with a deltagerr value of 0.

**Comment by mmundy42** [comment]
Also, I noticed the is_obsolete and linked_reaction fields were removed from reactions.default.tsv and reactions.plantdefault.tsv.  Are those fields optional now?

**Comment by samseaver** [comment]
If I remember rightly, those fields were specifically created for the master list.

**Comment by mmundy42** [comment]
Just a note that a value of "null" sometimes needs to be converted to a value to work with the biochemistry objects.  The compounds.master.tsv file has 9,602 compounds with "null" for the charge but the Bio::KBase/ObjectAPI/KBaseBiochem/Compound object requires that charge is a number.  And the add_compound() method in Bio::KBase/ObjectAPI/KBaseBiochem/Biochemistry requires an empty array if there are no aliases.

**Comment by samseaver** [comment]
We went will null instead of the previous default which was 10000000. The idea is to indicate that charge is not available, but in the event of building the biochemistry object, we'd have to pick a default number to use instead.  I'm against picking zero because it's a valid charge and one we don't want to use for compounds with an unknown charge, so we could revert to using 10000000. The high number at least makes it easy to pick out why some reactions are unbalanced.

**Comment by cshenry** [comment]
I think we should alter the object API and specs to allow undefined values I think�
Also, I find it dubious for a compound to have an unknown charge. Unknown formula or structure maybe� but unknown charge?
If the formula is �R�, I think you can reasonably safely say the charge is 0.

**Comment by samseaver** [comment]
OK, so you're comfortable with my setting the default value for charge to zero?

**Comment by chian** [comment]
As long as there is another indicator for unknown, I think this sounds good

**Comment by mmundy42** [comment]
@samseaver, anything else to do with this issue?  When building objects from the files, if a "null" is found, I don't specify the value and let the object pick the default value.

**Comment by samseaver** [comment]
Ya, seems redundant at the moment.
