### ISSUE TITLE
compartment indices don't match reaction DB

### ISSUE THREAD

**Issue by gregmedlock** [ModelSEED/ModelSEEDDatabase#30]
The compartment indices specified in compartments.master.tsv and compartments.default.tsv don't match those in reactions.master.tsv (or any reaction DB file, for that matter). The reaction DB files only contain 0, 1, and 2 for compartment indices in the equation, stoichiometry, and definition.

What the indices in the reaction DB files currently correspond to is unclear, since 1 is used interchangeably for extracellular and periplasm. 2 appears to be unique to Ton transport system reactions.

**Comment by samseaver** [comment]
I understand this is an old comment, I apologize for never having replied. We were in a transition from using letters for original compartments to using numbers for generic compartments. We no longer store the original compartments in the biochemistry (in the new reactions.tsv) but do try to capture them in the template files.

**Comment by gregmedlock** [comment]
Thanks for the update!  New approach looks nice/clean, btw.
