### ISSUE TITLE
Templates/Core files have inconsistent compartment names

### ISSUE THREAD

**Issue by tfarrah** [ModelSEED/ModelSEEDDatabase#31]
I'm using Build_Model_Template.py to create template files for the ProbModelSEED software. It has run successfully for GramNegative, GramPositive, and Microbial, but failed on Core:

Traceback (most recent call last):
  File "./Build_Model_Template.py", line 91, in <module>
    helper.readReactionsFile(reactionsFile, includeLinenum=False)
  File "/users/tfarrah/ModelSEEDDatabase/scripts/TemplateHelper.py", line 453, in readReactionsFile
    raise CompartmentNotFoundError('Compartment %s not found in current list' %(compartmentIds[cindex]))
TemplateHelper.CompartmentNotFoundError: Compartment c not found in current list

I saw that, for Core, Compartments.tsv lists compartments c0 and e0, but Reactions.tsv uses compartments c and e.

To fix, I replaced all instances of c0 with c in Compartments.tsv and BiomassCompounds.tsv

Is this a reasonable fix?

**Comment by mmundy42** [comment]
Yes, that is a reasonable fix. The original versions of the template files used "c0" and "e0" for compartment IDs. We later changed the IDs to "c" and "e" since a template should not reference the compartment number in a community model. We must have missed the Compartments.tsv and BiomassCompounds.tsv files in the Core template.

**Comment by tfarrah** [comment]
Thanks.
Would you like me to push my changes? I'm a Github newbie so I don't know what you'd need to do to give me permission to do that. I tried pushing them but not surprisingly got the message " Permission to ModelSEED/ModelSEEDDatabase.git denied to tfarrah"

**Comment by samseaver** [comment]
Terry, the Git approach requires you to fork the repository and submit a pull request for the project owners to merge the changes. This website explains it:

https://help.github.com/articles/fork-a-repo/
