### ISSUE TITLE
Fructanohydrolase reaction error

### ISSUE THREAD

**Issue by gregmedlock** [ModelSEED/ModelSEEDDatabase#34]
Hello,

The reaction rxn06945 appears as:

H2O -> Levan n

Which has obvious mass balance issues. The name associated with the reaction is 2,6-beta-D-Fructan fructanohydrolase. It looks like any of the 'M' units of Levan were stripped when transferring from KEGG (http://www.genome.jp/dbget-bin/www_bget?rn:R05624), giving the current reaction.

**Comment by samseaver** [comment]
Hi Greg, where are you seeing this reaction?

**Comment by gregmedlock** [comment]
It appears in reactions.master.tsv. I found it while checking a few gap-filled reconstructions for leaks.

**Comment by samseaver** [comment]
We keep unbalanced reactions in that spreadsheet, as the "master" sheet, for future reference and expansion, indeed, the "status" column holds the mass balance results; we only include reactions that are "OK" in the templates for model construction and gapfilling.

Are you saying that you got this reaction _in_ a model as a result of gapfilling?

**Comment by samseaver** [comment]
I just checked, we don't have this reaction in either microbial template.
