### ISSUE TITLE
List of issues surrounding merging of Complex Roles

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/ModelSEEDDatabase#4]
With the changes made in this commit: https://github.com/ModelSEED/ModelSEEDDatabase/commit/3e061cc13d47fad6180d9701e3b059553d36751f one can generate a full JSON object that contains both the ModelSEED and newly generated KEGG complex roles. Again, the output is not added within the scope of this repository, as I guess its home should be in the ProbModelSEED repository.

There are several issues:
1) Several role aliases matched a ModelSEED role that did not have the same name as the new role name, these are conflicts and have to be resolved.

2) I did not include role and complex aliases yet

3) We have to come up with a consistent approach to using identifiers for both complexes and roles in ProbModelSEED as its currently a mixture of formats.

4) The file that Mike generated has several possible sources for the "type" field in a complexrole. As of now, I'm using the last type column that is labelled "type", but we will need to re-visit this once the specifications for the Mapping object in a PATRIC workspace has been updated.

**Comment by mmundy42** [comment]
Before running the new Build_Mapping_JSONs.pl that was added by the referenced commit, you need to run Print_ModelTemplate_from_Workspaces.pl?  And do I still need to use Build_ModelTemplate_Mapping_JSONs.pl?

**Comment by samseaver** [comment]
Well the question is whether you'd want to generate the files for yourself, or if you'd like me to add the ones I generated to this/another repository. I can simply email you the JSON itself too.

**Comment by samseaver** [comment]
In any case, the process you'd have to take would be:

1) Run Print_ModelTemplate_from_Workspaces.pl
2) Copy the files from the "old" template (I'm assuming Mappings/default-mapping) to a new one (I used Mappings/probmodelseed-mapping)
3) Run Merge_ComplexRoles.pl (the filenames are hard-coded so you may want to modify as you wish)
4) Add a line to Mappings/Mapping_Data.txt to include the top-level metadata
5) Run Build_Mapping_JSONs.pl

**Comment by samseaver** [comment]
It has occurred to me that one should ensure that the reactions used in these mappings are correctly represented in the resulting ModelTemplate. I'll probably add another script that will copy and extend the default ModelTemplate.

**Comment by samseaver** [comment]
I'm closing this issue, it seems like its aged beyond recognition, and with the work proceeding on the new ModelTemplate, outdated.
