### ISSUE TITLE
Malformed InChI

### ISSUE THREAD

**Issue by JamesJeffryes** [ModelSEED/ModelSEEDDatabase#41]
_From @smoretti on October 14, 2016 13:40_

We found about 1208 InChI strings that cannot be read by the software Chemaxon from the ModelSEED compound data.
E.g.
- cpd00194 InChI=1S/C12H14N2.Cl2H2/c1-13-7-3-11(4-8-13)12-5-9-14(2)10-6-12;;/h3-10H,1-2H3;2*1H/q+2;;
- cpd00271    InChI=1S/C6N6.Fe/c6*1-2;/q;;;;;;-3
- cpd00418    InChI=1S/NO/c1-2/rad

_Copied from original issue: ModelSEED/ModelSEED-UI#60_

**Comment by JamesJeffryes** [comment]
_From @smoretti on January 6, 2017 12:48_

Also
* cpd00766 InChI=1S/C6H7O6/c7-1-2(8)5-3(9)4(10)6(11)12-5/h2,5,7-8,10H,1H2/t2-,5+/m0/s1/rad
* cpd26335 InChI=1S/AsHO3.H4O2.O.Sb2/c2-1(3)4;;;;;/h2H;2*1H2;;;/q-2;;;;2*+2/CRV:3-1,4-1;;;;;

**Comment by JamesJeffryes** [comment]
Failure to parse these strings is caused by a suffix appended to the InChI string to prevent certain compounds from being merged. To remedy this I'll split this suffix into a new column and update the InChIs

**Comment by samseaver** [comment]
We can simply retrieve the original InChIs as listed in the Structures directory rather than attempt to re-parse the ones in the 'structure' column

**Comment by smoretti** [comment]
Great, thanks
