### ISSUE TITLE
Some reactions don't have reactants and/or products

### ISSUE THREAD

**Issue by JamesJeffryes** [ModelSEED/ModelSEEDDatabase#42]
_From @smoretti on October 7, 2016 14:17_

Hi

Some reactions don't have reactants and products.
E.g.
- rxn14154
- rxn00000
- rxn14393

Some reactions don't have reactants or products.
E.g.
- rxn13783

_Copied from original issue: ModelSEED/ModelSEED-UI#55_

**Comment by JamesJeffryes** [comment]
_From @samseaver on October 7, 2016 15:2_

Hi Sebastien, I'm responsible for maintaining the master list of reactions and compounds at ModelSEEDDatabase, but I haven't been updating the databases that are reached using the ModelSEED API.

But to compound things, there are probably several ways in which you can do so, can you let me know which repository you are using for the API, and which URLs you are using to instantiate the service?

Thanks
Sam

**Comment by JamesJeffryes** [comment]
_From @smoretti on October 7, 2016 15:17_

I use https://www.patricbrc.org/api/model_compound and https://www.patricbrc.org/api/model_reaction
The same URLs used on the ModelSeed.org web site

**Comment by samseaver** [comment]
We balance out identical reactants and products, so if a compound is on both side of the equations, and in the same compartment, we remove it. The end result means that some reactions are either empty or one-sided, but, if this were the case, they would've been unusable for metabolic modeling anyway.
