### ISSUE TITLE
Compound with unexpected characters in formula

### ISSUE THREAD

**Issue by JamesJeffryes** [ModelSEED/ModelSEEDDatabase#43]
_From @smoretti on October 7, 2016 15:11_

Hi

I found some compounds with unexpected characters in formula
E.g.
- AsH-1O3.H4O2.O.Sb2  what is **-**?
- H2O6P2*2 is `*` for polymer with n=2 ???
- C11H14NO9R4* what is `*` there?

_Copied from original issue: ModelSEED/ModelSEED-UI#58_

**Comment by JamesJeffryes** [comment]
_From @smoretti on October 14, 2016 13:55_

Also for cpd19876 with **C33H60I2O10n** Is _n_ for the whole formula?

**Comment by mmundy42** [comment]
Here are more compounds with unexpected characters in the formula:

cpd11658: C12H20O10*2
cpd11720: C5H11O7P*2
cpd11746: C6H10O5*2
cpd11851: C6H10O5*2
cpd12039: H2O6P2*2
cpd12077: C5H8*2
cpd12120: C6H10O5*2
cpd12148: C6H10O5*2
cpd12163: C12H20O11*2
cpd12234: C6H11O6*
cpd12434: C25H45NO8R*
cpd12511: C24H41O21*
cpd12759: C5H7NO3*2
cpd19503: C10H10N5O6PS2.Mo.O2
cpd19935: CH3.Hg
cpd20971: C45H57N5O13.Co
cpd21288: C19H22N8O13P2S2.Mo.O2
cpd22240: C62H90N13O17P2.C10H12N5O3.Co
cpd24099: C61H86N13O14P.Co
cpd24567: Pb.S
cpd24797: C42H47N6O14.Ni
cpd24798: C42H47N6O14.Ni
cpd24958: C42H41N5O15.Fe
cpd25050: C10H10N5O6PS2.Mo.O.S
cpd25093: C7H3NO2S2.ClH.Cu
cpd25094: C7H2NO2S2.Cl2H2.Cu
cpd25095: C8H2Cl3NO2S2.Cl2H2.Cu
cpd25097: C7H3NO3S.ClH.Cu
cpd25539: C42H37N4O16.Co
cpd25541: C45H53N4O14.Co
cpd26289: Cl3.Fe
cpd26290: Cl2.Fe
cpd30665: C25H30N3.ClH
cpd30678: C8H8Cl2N2S.ClH

**Comment by samseaver** [comment]
This was fixed in a recent PR where all formulas were "merged".
