### ISSUE TITLE
Compound with weird charge

### ISSUE THREAD

**Issue by JamesJeffryes** [ModelSEED/ModelSEEDDatabase#44]
_From @smoretti on October 7, 2016 15:12_

Some compounds have a charge value of 10000000
e.g. **cpd11414**

Is it a kind of default value?
It is a bit counterintuitive.

_Copied from original issue: ModelSEED/ModelSEED-UI#59_

**Comment by JamesJeffryes** [comment]
@samseaver Would it be possible for the default value going forward to be "nan" "null" or ""? Those might be more intuitive to our users.

**Comment by samseaver** [comment]
Superficially yes we could change this, but I think Chris' underlying MFAToolkit recognizes these defaults, we'd have to revisit with him.
