### ISSUE TITLE
Merge all alias files

### ISSUE THREAD

**Issue by JamesJeffryes** [ModelSEED/ModelSEEDDatabase#49]
Biochemistry
/Aliases
We want to keep only aliases for main databases, clean current published models and keep only BIGG
Rxn_aliases.tsv: modelseed_id, ext_id, source
Cpd_aliases.tsv: modelseed_id, ext_id, source

**Comment by samseaver** [comment]
Done, but with an extra column, for the time being, for "old" modelseed ids (to find conflicts)
