### ISSUE TITLE
Malformed EC strings in JSON

### ISSUE THREAD

**Issue by JamesJeffryes** [ModelSEED/ModelSEEDDatabase#50]
_From @smoretti on October 7, 2016 14:47_

Hi

There are lots of badly formatted EC numbers in the JSON returned by the API.
Some have spaces in front of the EC number; some have several EC number per entry in the EC JSON array, separated by 
- *\* or **
- *\* / *\* 
- several white spaces

some EC strings end with 
- **,**
- **)** characters

_Copied from original issue: ModelSEED/ModelSEED-UI#56_

**Comment by samseaver** [comment]
These are fixed
