### ISSUE TITLE
possible compound name issue

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ModelSEEDDatabase#7]
Just reporting that I saw an odd "[a]" in the middle of `Benzo[a]pyrene-4,5-oxide[c]` in reaction `rxn04886`

**Comment by chian** [comment]
https://en.m.wikipedia.org/wiki/Benzopyrene

These are unfortunately legitimate. I'm hoping we aren't using names to mark compartments and that it's part of the object...

**Comment by samseaver** [comment]
The regex we use splits equation strings first based on the ' + ' string that separates compounds, and then finds the compartments at the end of the compound strings, so in this case, we shouldn't be getting an error, are we?

**Comment by nconrad** [comment]
ok, I'm not aware of any errors, I figured I report to be safe.  Closing.
