### ISSUE TITLE
Pathways not assigned to reactions in flat files

### ISSUE THREAD

**Issue by lcottret** [ModelSEED/ModelSEEDDatabase#96]
Hi!

I get SBML files from a collaborator who built them with ModelSeed. However, they don't contain the link between reactions and subsystems. I browsed the reactions.tsv and reactions.json files but the pathways attribute is always equal to null... How can I get this information ?

Regards,
Ludovic Cottret

**Comment by samseaver** [comment]
We corresponded by email and I pointed Ludovic to:
Biochemistry/Pathways/ModelSEED_Subsystems.tsv
